server:
  port: 9090
spring:
  application:
    name: spring-aspectj-aop
  datasource:
    url: jdbc:mysql://localhost:3306/omnishore?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: update